companies = {
    # US Tech
    "Apple Inc.": "AAPL",
    "Microsoft Corporation": "MSFT",
    "Tesla Inc.": "TSLA",
    "Amazon.com Inc.": "AMZN",
    "Alphabet Inc. (Google)": "GOOGL",
    "Meta Platforms Inc. (Facebook)": "META",
    "Netflix Inc.": "NFLX",
    "NVIDIA Corporation": "NVDA",
    "Adobe Inc.": "ADBE",
    "Intel Corporation": "INTC",

    # US Finance & Commerce
    "JPMorgan Chase & Co.": "JPM",
    "Visa Inc.": "V",
    "Mastercard Incorporated": "MA",
    "Goldman Sachs Group": "GS",
    "American Express": "AXP",
    "PayPal Holdings": "PYPL",
    "Walmart Inc.": "WMT",
    "The Home Depot": "HD",
    "Coca-Cola Company": "KO",
    "PepsiCo Inc.": "PEP",
    "McDonald's Corporation": "MCD",
    "Nike Inc.": "NKE",
    "Costco Wholesale": "COST",
    "Procter & Gamble Co.": "PG",
    "Johnson & Johnson": "JNJ",
    "Pfizer Inc.": "PFE",

    # Indian Giants (with .NS suffix for NSE)
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services": "TCS.NS",
    "Infosys Ltd.": "INFY.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Wipro Ltd.": "WIPRO.NS",
    "State Bank of India": "SBIN.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Larsen & Toubro": "LT.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "ITC Ltd.": "ITC.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "Hindustan Unilever": "HINDUNILVR.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "Oil and Natural Gas Corporation": "ONGC.NS",

    # Cryptocurrencies
    "Bitcoin (BTC)": "BTC-USD",
    "Ethereum (ETH)": "ETH-USD",
    "Dogecoin (DOGE)": "DOGE-USD",
    "Solana (SOL)": "SOL-USD",
    "Ripple (XRP)": "XRP-USD",
}
